name: ecommerce
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # UI / UX
  cupertino_icons: ^0.1.3
  toast:
  flutter_slidable: ^0.5.7
  animated_text_kit: ^2.2.0
  smooth_page_indicator: ^0.2.0
  # firebase
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  # state management
  provider: ^4.0.0
  # database
  moor_flutter: ^3.1.0
  shared_preferences: ^0.5.10
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  moor_generator: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/addtocart.jpg
    - assets/getstart.jpg
    - assets/goinshop.jpg

  fonts:
    - family: hind
      fonts:
        - asset: assets/fonts/Hind-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
